# fly.toml app configuration file generated for rdiazlugo-pocketbase on 2025-07-12T02:26:40+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rdiazlugo-pocketbase'
primary_region = 'fra'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
 dockerfile = "Dockerfile"

[mounts]
  source = "data_pb"
  destination = "/pb_data"

[http_service]
  internal_port = 8080
  force_https = true
  # auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

[[vm]]
  size = 'shared-cpu-1x'
