name: Fly Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      # - run: flyctl launch --no-deploy --config pocketbase/fly.toml
      - run: flyctl deploy --remote-only --config pocketbase/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_2ND_ACCOUNT }}
